name: Generate IoT Dashboard ESP 32

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  generate-dashboard:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Generate IoT Dashboard
      - name: Generate IoT Dashboard
        uses: 4211421036/iotgithub@v1.0.1
        with:
          json_filename: 'data.json'
          html_filename: 'index.html'
          css_filename: 'styles.css'
          site_title: 'IoT Dashboard'
          chart_title: 'IoT Data Chart'

      # Step 3: List files (untuk debug)
      - name: List files
        run: |
          ls -la
